"""Emit biological dataset + cohort registries, the canonical dataset registry,
and the corpus totals. Counts confirmed by direct inspection (subagent B/C/A +
own checks); every dataset row cites its source path. Read-only, deterministic.
"""
from __future__ import annotations
from pathlib import Path
import pandas as pd

OUT = Path("/Users/surajpg/projects/GAIRA/data_audit"); OUT.mkdir(exist_ok=True)
RAW = "/Volumes/SSD_Rad/GAIRA_DATA/raw"

# ── biological_dataset_registry.csv ──
bio = [
 dict(dataset_id="diabetes_plasma_ev_sers",domain="plasma-EV",biosample="plasma EV",disease_or_perturbation="T2D (Impact/Strong-D arms)",modality="SERS",substrate="Ag",excitation_nm="",n_patients="63(39+24; 40 meta Impact)",n_donors=63,n_samples=63,n_timepoints=1,n_conditions=2,n_raw_spectra=31834,n_processed_spectra=63,spectra_per_sample_distribution="441(x32),1089(x5),811,882",technical_replicates="map scans",biological_replicates="1 sample/patient",paired_samples="no",longitudinal="no",metadata_available="yes(bmi,hba1c,race,sex,age)",labels_available="Impact/Strong-D",currently_used_v3_1="YES(63 per-sample)",currently_used_src_gaira="DB biosample",used_for_global_scale_fit="YES",used_only_for_projection="no",known_leakage_or_duplication_risk="map scans not independent; 1 Impact patient no raw"),
 dict(dataset_id="shine_ev_sers",domain="EV cell-line",biosample="EV/cell",disease_or_perturbation="hepatotoxicity APAP dose x day",modality="SERS",substrate="Ag",excitation_nm="",n_patients="cell-line",n_donors="cell-line",n_samples="~41 wells",n_timepoints="D0,D1,D2(no D3/D7)",n_conditions="4 doses x 3 days",n_raw_spectra=23646,n_processed_spectra=23646,spectra_per_sample_distribution="810-2284 per (set,day,dose)",technical_replicates="single-point map scans",biological_replicates="cell wells",paired_samples="no",longitudinal="D0-D2",metadata_available="dose,day",labels_available="D{0,1,2}_C{0,10,20,40}",currently_used_v3_1="YES(8 class means, reduced-dim)",currently_used_src_gaira="DB",used_for_global_scale_fit="no",used_only_for_projection="yes(collapsed)",known_leakage_or_duplication_risk="3-axis collapse; no per-sample mean; not recomputable"),
 dict(dataset_id="small2023_ev",domain="EV cell-line",biosample="cell-line EV mixtures",disease_or_perturbation="two-component EV mixtures",modality="SERS",substrate="Ag",excitation_nm="",n_patients="cell-line",n_donors="probes",n_samples="5-6 cell lines/fractions",n_timepoints=1,n_conditions="6 mixture fractions",n_raw_spectra="105140 (P1 19557 + P2 85583)",n_processed_spectra="9467 + 85583",spectra_per_sample_distribution="c00..c100",technical_replicates="augmented/synthetic",biological_replicates="few cell lines",paired_samples="no",longitudinal="no",metadata_available="fraction",labels_available="cell-line/fraction",currently_used_v3_1="no",currently_used_src_gaira="pilot1/1b (DB)",used_for_global_scale_fit="no",used_only_for_projection="no",known_leakage_or_duplication_risk="AUGMENTED (identical 14884 counts); NOT independent measurements"),
 dict(dataset_id="cca_hcc_lm_serum_sers",domain="serum",biosample="serum",disease_or_perturbation="liver cancers HA/CCA/HCC/LM",modality="SERS",substrate="Ag nanosensor",excitation_nm="",n_patients=218,n_donors=218,n_samples=218,n_timepoints=1,n_conditions=4,n_raw_spectra="234(226 bio+8 dilution)",n_processed_spectra="213 bsv/212 mean",spectra_per_sample_distribution="~1/sample (SER-CCA-58 x2)",technical_replicates="per-sample avg",biological_replicates="1/patient",paired_samples="no",longitudinal="no",metadata_available="class",labels_available="NC/CCA/HCC/LM",currently_used_v3_1="YES(212 patients, serum liver)",currently_used_src_gaira="pilot4_1 (DB)",used_for_global_scale_fit="YES(212)",used_only_for_projection="no",known_leakage_or_duplication_risk="SER-CCA-58 dup (213 vs 212); SER-LM-11 id mismatch"),
 dict(dataset_id="hcc_serum",domain="serum",biosample="serum",disease_or_perturbation="CTR vs H0T (paired)",modality="SERS",substrate="Ag batch A/B/C",excitation_nm="",n_patients=91,n_donors=91,n_samples=91,n_timepoints=1,n_conditions=2,n_raw_spectra=144,n_processed_spectra=0,spectra_per_sample_distribution="1-2/sample(53 paired)",technical_replicates="CTR/H0T pairs",biological_replicates="91",paired_samples="yes(53)",longitudinal="no",metadata_available="batch,class",labels_available="CTR/H0T",currently_used_v3_1="no",currently_used_src_gaira="SKIPPED in registry",used_for_global_scale_fit="no",used_only_for_projection="no",known_leakage_or_duplication_risk="registered but skipped"),
 dict(dataset_id="covid_serum_raman",domain="serum",biosample="serum",disease_or_perturbation="COVID/Suspected/Healthy",modality="Raman",substrate="none(label-free)",excitation_nm="",n_patients="~157",n_donors="~157",n_samples="~157",n_timepoints=1,n_conditions=3,n_raw_spectra="465(159+156+150)+12 tube",n_processed_spectra="309(pilot5)",spectra_per_sample_distribution="~3 experimenter-avg/patient",technical_replicates="3 experimenters x5 avg",biological_replicates="~157",paired_samples="no",longitudinal="no",metadata_available="group",labels_available="COVID/Suspected/Healthy",currently_used_v3_1="no",currently_used_src_gaira="pilot5 (DB)",used_for_global_scale_fit="no",used_only_for_projection="yes",known_leakage_or_duplication_risk="pilot5 treats each spectrum as 'patient'(309); Suspected+Tube dropped; true pts ~103"),
 dict(dataset_id="ovarian_plasma_raman_sers",domain="plasma",biosample="plasma",disease_or_perturbation="ovarian cancer vs healthy",modality="Raman+SERS(paired)",substrate="AuNPs(SERS)",excitation_nm="",n_patients=55,n_donors=55,n_samples=55,n_timepoints=1,n_conditions=2,n_raw_spectra="770(385 Raman+385 SERS)",n_processed_spectra=0,spectra_per_sample_distribution="~7 tech/patient x2 modality",technical_replicates="yes",biological_replicates="55",paired_samples="yes(Raman+SERS)",longitudinal="no",metadata_available="class",labels_available="OC/HC",currently_used_v3_1="no",currently_used_src_gaira="no",used_for_global_scale_fit="no",used_only_for_projection="no",known_leakage_or_duplication_risk="paired modality; ID cross-map unclear"),
 dict(dataset_id="ucla_saliva_sev_gc",domain="salivary sEV",biosample="saliva EV",disease_or_perturbation="gastric cancer",modality="Raman(single-vesicle)",substrate="none",excitation_nm=785,n_patients=18,n_donors="18(17 GC+1 healthy)",n_samples=18,n_timepoints=1,n_conditions=2,n_raw_spectra=2231,n_processed_spectra=0,spectra_per_sample_distribution="35-326 single-vesicle/donor",technical_replicates="single-vesicle scans",biological_replicates=18,paired_samples="no",longitudinal="no",metadata_available="donor",labels_available="GC/healthy",currently_used_v3_1="no",currently_used_src_gaira="global_v2",used_for_global_scale_fit="no",used_only_for_projection="no",known_leakage_or_duplication_risk="severe imbalance (1 healthy donor)"),
 dict(dataset_id="coeliac_faecal_sers",domain="faecal",biosample="faeces",disease_or_perturbation="coeliac CD/CTR/GFD",modality="SERS",substrate="Ag",excitation_nm="",n_patients=27,n_donors=27,n_samples=27,n_timepoints=1,n_conditions=3,n_raw_spectra="30(27 subj+3 ref)",n_processed_spectra=0,spectra_per_sample_distribution="1/subject",technical_replicates="no",biological_replicates=27,paired_samples="no",longitudinal="no",metadata_available="sex,age,group",labels_available="CD/CTR/GFD",currently_used_v3_1="no",currently_used_src_gaira="global_v2",used_for_global_scale_fit="no",used_only_for_projection="no",known_leakage_or_duplication_risk="small n"),
 dict(dataset_id="stroke_urine_sers",domain="urine",biosample="urine",disease_or_perturbation="stroke/infarction vs control",modality="SERS",substrate="Ag",excitation_nm="532;633",n_patients=132,n_donors=132,n_samples=132,n_timepoints=1,n_conditions=2,n_raw_spectra="482 matrix / 210 wdf",n_processed_spectra=0,spectra_per_sample_distribution="paired 532/633",technical_replicates="2 excitations paired",biological_replicates=132,paired_samples="yes(532/633)",longitudinal="no",metadata_available="BMI,HTN,DM,AF,smoking",labels_available="1=77/0=55",currently_used_v3_1="no",currently_used_src_gaira="global_v2",used_for_global_scale_fit="no",used_only_for_projection="no",known_leakage_or_duplication_risk="rar-recovered"),
 dict(dataset_id="mycoplasma_na_sers",domain="microbial",biosample="pathogen culture",disease_or_perturbation="nucleic-acid SERS specificity",modality="SERS",substrate="Ag",excitation_nm="",n_patients="n/a",n_donors="44 strains",n_samples="44 strains",n_timepoints=1,n_conditions="44+controls",n_raw_spectra="521(471 org+50 ctrl)",n_processed_spectra=0,spectra_per_sample_distribution="~10/strain",technical_replicates="yes",biological_replicates="44 strains",paired_samples="no",longitudinal="no",metadata_available="species/strain",labels_available="46 labels",currently_used_v3_1="no",currently_used_src_gaira="global_v2",used_for_global_scale_fit="no",used_only_for_projection="no",known_leakage_or_duplication_risk="not human"),
 dict(dataset_id="single_vesicle_ev_raman",domain="EV cell-line",biosample="cell-line EV",disease_or_perturbation="HRAS vs ctrl",modality="Raman(single-vesicle)",substrate="none",excitation_nm=785,n_patients="cell-line",n_donors="6 preps",n_samples=6,n_timepoints=1,n_conditions=2,n_raw_spectra=525,n_processed_spectra=0,spectra_per_sample_distribution="single-vesicle",technical_replicates="yes",biological_replicates="6 preps",paired_samples="no",longitudinal="no",metadata_available="class",labels_available="ctrl/HRAS",currently_used_v3_1="no",currently_used_src_gaira="global_v2",used_for_global_scale_fit="no",used_only_for_projection="no",known_leakage_or_duplication_risk="rar-recovered"),
 dict(dataset_id="LAB_DATA/Cracked_Au",domain="in-house lab",biosample="EV/RNA + 4-MBA reporter",disease_or_perturbation="porous-Au substrate dev",modality="SERS",substrate="cracked/porous Au",excitation_nm="",n_patients="n/a",n_donors="n/a",n_samples="8 wells",n_timepoints=1,n_conditions="EV/RNA/Blank + 4-MBA",n_raw_spectra="5252(2500 4-MBA + 2752 EV/RNA/Blank)",n_processed_spectra=0,spectra_per_sample_distribution="~320/well map",technical_replicates="map scans",biological_replicates="8 wells",paired_samples="no",longitudinal="no",metadata_available="well",labels_available="EV/RNA/Blank",currently_used_v3_1="no",currently_used_src_gaira="no(unwired)",used_for_global_scale_fit="no",used_only_for_projection="no",known_leakage_or_duplication_risk="in-house; 2500 non-bio 4-MBA; wired nowhere"),
]
pd.DataFrame(bio).to_csv(OUT/"biological_dataset_registry.csv", index=False)

# ── biological_cohort_registry.csv (used cohorts) ──
coh = [
 ("cca_hcc_lm_serum_sers","HA(healthy adult/NC)","serum control",48,48,"~48","n/a","n/a","no","pilot4_1 patient_level_bsv"),
 ("cca_hcc_lm_serum_sers","CCA","cholangiocarcinoma",67,67,"67(+SER-CCA-58 dup)","n/a","n/a","no","pilot4_1"),
 ("cca_hcc_lm_serum_sers","HCC","hepatocellular carcinoma",49,49,49,"n/a","n/a","no","pilot4_1"),
 ("cca_hcc_lm_serum_sers","LM","liver metastasis",49,49,49,"n/a","n/a","no","pilot4_1"),
 ("diabetes_plasma_ev_sers","OWD(Impact)","overweight diabetic arm",39,39,"441-1089 scans","1","OWD","no","pilot2 sample_query"),
 ("diabetes_plasma_ev_sers","NWD(Strong-D)","normal-weight diabetic arm",24,24,"441 scans","1","NWD","no","pilot2"),
 ("shine_ev_sers","D0_C0..D2_C40","dose x day EV",0,"~41 wells","810-2284/cell","D0,D1,D2","C0/10/20/40","no","pilot3"),
 ("covid_serum_raman","COVID/Healthy","confirmed vs control","~103","309(as spectra)","~3/patient","1","group","no","pilot5"),
]
pd.DataFrame(coh, columns=["dataset_id","cohort_name","cohort_definition","n_patients","n_samples","n_spectra","timepoints","dose_or_condition","paired_status","source_table"]).to_csv(OUT/"biological_cohort_registry.csv", index=False)

# ── canonical_dataset_registry.csv (all roles) ──
can = [
 # id, canonical_name, role, secondary, domain, biosample, raman_or_sers, raw_path, raw_files, spectral_records, indep_samples, indep_patients, indep_analytes, used_v3_1, used_src, tier, provenance, limitations
 ("ramanbiolib_202","RamanBioLib reference (202 rows/141 compounds)","molecular_grounding","","reference","pure compounds","Raman",f"{RAW}/ramanbiolib + repo grounding_molecule_*.csv","202","202 rows / 141 unique","141","n/a","141","YES(space,coverage)","reference_metadata(DB)",1,"complete(DOI 10.1002/jrs.1734)","spontaneous Raman only; 6/11 axes inherited splits"),
 ("warehouse_43","Grounding evidence warehouse","molecular_grounding","supporting_literature","mixed","mixed","mixed",".../warehouse_source_registry.csv","43 rows / 28 unique ids","4 sources w/ measured","n/a","n/a","~85","YES(corpus map)","grounding_search(DB)",1,"partial","30 rows=15 duplicated papers; only 1 has structured spectra"),
 ("adenine_sers_control","Adenine bAgNP dose","calibration","molecular_grounding","reference","adenine","SERS",f"{RAW}/adenine_sers_control","17","17","6-7 conc","n/a","1","YES(live)","calibration/loaders",1,"complete","single substrate; dampen unvalidated"),
 ("european_adenine","European multi-instrument adenine","calibration","","reference","adenine","SERS",f"{RAW}/european_multi_instrument_adenine","7032 txt + ILSdata","3516/7032","43 conc x 15 labs","n/a","1","ablation only","unknown",1,"complete","4 substrates/2 lasers UNUSED (demo blind)"),
 ("ergothioneine_serum","Ergothioneine dose","calibration","","reference","ergothioneine","SERS",f"{RAW}/ergothioneine_serum","1(55 rows)","55","11 conc x5","n/a","1","YES(live)","calibration/loaders",1,"complete","thiol boost heuristic"),
 ("serum_ag_colloids","Gobbato serum Ag-colloid (uricase/hypoxanthine)","calibration","molecular_grounding+biological","serum","serum+metabolites","SERS",f"{RAW}/serum_ag_colloids","907 txt","907","1 serum pool + 53 metabolites + 81 donors","n/a","53","YES(SAEL contrasts)","serum_ag_colloids_grounding(DB 368)",1,"complete","uricase inconsistent; empty raw grounding folder (in DB)"),
 ("cspp_serum","CSPP serum spikes","calibration","","serum","pooled serum","SERS",f"{RAW}/cspp_serum","1056+5 fig","1056","Bkg/Erg/Hyp","n/a","2","YES(SAEL)","unknown",1,"complete","conc confounded"),
 ("sers_metabolite_63","63-metabolite SERS panel (NIHMS1547448)","molecular_grounding","calibration","reference","metabolites","SERS",f"{RAW}/sers_metabolite_63","2 xlsx","63","n/a","n/a","63","grounding(64)","grounding",1,"complete","1 avg/analyte"),
 ("amino_acid_raman_grounding","20-analyte amino-acid Raman","molecular_grounding","calibration","reference","AA/metabolites","Raman",f"{RAW}/amino_acid_raman_grounding","2 xlsx","20","n/a","n/a","20","grounding(20)","grounding",1,"complete","1/analyte; Raman"),
 ("metabolite_sers63_support","Fityk fit products (NOT spectra)","supporting_literature","","reference","fit products","n/a",f"{RAW}/metabolite_sers63_support","127","0 spectra","n/a","n/a","n/a","no","no",2,"complete","peak-fit products, not measured spectra"),
 ("otc_drugs","OTC drug Raman","calibration","","reference","drugs","Raman",f"{RAW}/otc_drugs","14 xlsx","300","3 drugs x2","n/a","3","no","drug_detection",1,"complete","non-biochemical"),
 ("serum_protocol_comparison","Serum protocol comparison","calibration","substrate_physics","serum","serum","SERS",f"{RAW}/serum_protocol_comparison","75 txt","75","5 protocols x3x5","n/a","n/a","no","calibration",1,"complete","matrix protocol study"),
 ("raman_knowledge_core","Raman knowledge core (ontology)","supporting_literature","substrate_physics","knowledge","n/a","n/a",f"{RAW}/raman_knowledge_core","7 csv","0 spectra","n/a","n/a","n/a","indirect","knowledge(DB peak_assignments 288)",2,"complete","ontology/knowledge, not spectra"),
 # biological (abbreviated; full detail in biological_dataset_registry.csv)
 ("diabetes_plasma_ev_sers","Diabetes plasma-EV SERS","biological_mixtures","","plasma-EV","EV","SERS",f"{RAW}/diabetes_plasma_ev_sers","3","31834","63","63","n/a","YES","DB pilot2",3,"complete","technical map scans; 39 raw vs 40 meta"),
 ("shine_ev_sers","SHINE EV-SERS hepatotox","biological_mixtures","","EV","EV/cell","SERS",f"{RAW}/shine_ev_sers","zip","23646","~41 wells","cell-line","n/a","YES(reduced)","DB pilot3",3,"complete","3-axis collapse; no mean spectra"),
 ("small2023_ev","small2023 cell-line EV mixtures","biological_mixtures","","EV","cell-line EV","SERS",f"{RAW}/small2023_ev","2 mat","105140","5-6 lines","cell-line","n/a","no","DB pilot1/1b",3,"complete","AUGMENTED synthetic mixtures"),
 ("cca_hcc_lm_serum_sers","CCA/HCC/LM/HA serum SERS","biological_mixtures","","serum","serum","SERS",f"{RAW}/cca_hcc_lm_serum_sers","234","234","218","218","n/a","YES(212)","DB pilot4_1",3,"complete","SER-CCA-58 dup"),
 ("hcc_serum","HCC serum CTR/H0T","biological_mixtures","","serum","serum","SERS",f"{RAW}/hcc_serum","144","144","91","91","n/a","no","SKIPPED",3,"complete","registered but skipped"),
 ("covid_serum_raman","COVID serum Raman","biological_mixtures","","serum","serum","Raman",f"{RAW}/covid_serum_raman","7","465","~157","~157","n/a","no","DB pilot5",3,"complete","pilot5 spectrum-as-patient"),
 ("ovarian_plasma_raman_sers","Ovarian plasma Raman+SERS","biological_mixtures","","plasma","plasma","Raman+SERS",f"{RAW}/ovarian_plasma_raman_sers","770","770","55","55","n/a","no","global_v2",3,"complete","paired modality"),
 ("ucla_saliva_sev_gc","UCLA saliva sEV gastric cancer","biological_mixtures","","salivary EV","saliva EV","Raman",f"{RAW}/ucla_saliva_sev_gc","2231","2231","18","18","n/a","no","global_v2",3,"complete","single-vesicle; 1 healthy donor"),
 ("coeliac_faecal_sers","Coeliac faecal SERS","biological_mixtures","","faecal","faeces","SERS",f"{RAW}/coeliac_faecal_sers","30","27","27","27","n/a","no","global_v2",3,"complete","small n"),
 ("stroke_urine_sers","Stroke urine SERS","biological_mixtures","","urine","urine","SERS",f"{RAW}/stroke_urine_sers","rar","482","132","132","n/a","no","global_v2",3,"complete","rar-recovered; paired 532/633"),
 ("mycoplasma_na_sers","Mycoplasma NA-SERS","biological_mixtures","","microbial","culture","SERS",f"{RAW}/mycoplasma_na_sers","1","521","44 strains","n/a","n/a","no","global_v2",3,"complete","not human"),
 ("single_vesicle_ev_raman","Single-vesicle EV Raman","biological_mixtures","","EV","cell-line EV","Raman",f"{RAW}/single_vesicle_ev_raman","rar","525","6 preps","cell-line","n/a","no","global_v2",3,"complete","rar-recovered"),
 ("lab_cracked_au","LAB_DATA Cracked/porous Au","biological_mixtures","substrate_physics","in-house","EV/RNA","SERS","/Volumes/SSD_Rad/LAB_DATA/Cracked_Au","5252","5252","8 wells","n/a","n/a","no","no",3,"complete","in-house; 2500 non-bio 4-MBA; unwired"),
 ("serum_ag_colloids_grounding","(empty raw; in DB)","molecular_grounding","","serum","serum","SERS",f"{RAW}/serum_ag_colloids_grounding","0(EMPTY)","368(DB)","n/a","n/a","n/a","YES(DB)","DB grounding_metadata",1,"processed-only","empty raw folder; data in duckdb"),
]
ccols=["dataset_id","canonical_name","top_level_role","secondary_role","domain","biosample","raman_or_sers","raw_path","raw_file_count","spectral_record_count","independent_sample_count","independent_patient_count","independent_analyte_count","currently_used_v3_1","currently_used_src_gaira","evidence_tier","provenance_status","known_limitations"]
pd.DataFrame(can, columns=ccols).to_csv(OUT/"canonical_dataset_registry.csv", index=False)

# ── gaira_corpus_totals.csv ──
totals = [
 dict(role="molecular_grounding",unique_datasets=6,unique_analytes="141(RamanBioLib)+63(met)+20(AA) overlap→~200 distinct",unique_patients=0,unique_biological_samples=0,independent_measured_spectra="202 ref + 468 grounding(DB)",technical_spectra=0,augmented_spectra=0,processed_duplicates="serum_ag_colloids_grounding empty raw",raman_spectra="202 ref(Raman)+20 AA",sers_spectra="448 grounding(adenine16+met64+serumAg368)",mixed_or_unknown_modality=0,currently_used_v3_1="202 table + warehouse + adenine",currently_used_src_gaira="reference_spectra + grounding (DB)"),
 dict(role="calibration",unique_datasets=7,unique_analytes="~80 distinct small molecules + 3 drugs",unique_patients=0,unique_biological_samples="serum pools/donors",independent_measured_spectra="~3726 SERS + 320 Raman (curated)",technical_spectra="European 7032 raw",augmented_spectra=0,processed_duplicates="metabolite63 fit-products excluded",raman_spectra=320,sers_spectra="~3726",mixed_or_unknown_modality=0,currently_used_v3_1="adenine,ergothioneine,serum-SAEL",currently_used_src_gaira="calibration/loaders"),
 dict(role="biological_mixtures",unique_datasets=13,unique_analytes=0,unique_patients="~760 human + cell/microbial units",unique_biological_samples="~760 human independent",independent_measured_spectra="~760 independent (of ~180k)",technical_spectra="~55k (diabetes 31834+shine 23646)",augmented_spectra="~105k (small2023)",processed_duplicates="pilot5 covid 309; SER-CCA-58",raman_spectra="covid+ovarian+ucla+single-vesicle ~4k",sers_spectra="~176k",mixed_or_unknown_modality="ovarian paired",currently_used_v3_1="serum-liver 212 + EV 63 + SHINE(reduced)",currently_used_src_gaira="DB biosample 185686"),
 dict(role="supporting_literature",unique_datasets=4,unique_analytes=0,unique_patients=0,unique_biological_samples=0,independent_measured_spectra=0,technical_spectra=0,augmented_spectra=0,processed_duplicates=0,raman_spectra=0,sers_spectra=0,mixed_or_unknown_modality=0,currently_used_v3_1="warehouse 30 papers (map)",currently_used_src_gaira="knowledge_chunks 96, peak_assignments 288, biomarker_claims 12"),
 dict(role="substrate_physics",unique_datasets="1 demo(5 rules)+1 prod(42 effects/47 registry)+atlas(8+phase4)",unique_analytes=0,unique_patients=0,unique_biological_samples=0,independent_measured_spectra=0,technical_spectra=0,augmented_spectra=0,processed_duplicates=0,raman_spectra=0,sers_spectra=0,mixed_or_unknown_modality=0,currently_used_v3_1="5 heuristic rules + prose atlas (wired)",currently_used_src_gaira="substrate/atlas engines DORMANT (no importer)"),
]
pd.DataFrame(totals).to_csv(OUT/"gaira_corpus_totals.csv", index=False)
print("wrote biological_dataset_registry (%d), biological_cohort_registry (%d), canonical_dataset_registry (%d), gaira_corpus_totals (5)"
      % (len(bio), len(coh), len(can)))
